INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("AL", transactionTotal, dollarAmountTotal);
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("AK", transactionTotal, dollarAmountTotal);
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("AR", transactionTotal, dollarAmountTotal);
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("AZ", transactionTotal, dollarAmountTotal);
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("CA", transactionTotal, dollarAmountTotal);
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("CO");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("CT");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("DE");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("FL");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("GA");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("HI");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("ID");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("IL");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("IN");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("IA");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("KS");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("KY");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("LA");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("ME");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("MD");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("MA");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("MI");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("MN");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("MS");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("MO");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("MT");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("NE");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("NV");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("NH");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("NJ");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("NM");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("NY");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("NC");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("ND");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("OH");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("OK");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("OR");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("PA");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("RI");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("SC");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("SD");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("TN");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("TX");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("UT");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("VT");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("VA");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("WA");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("WV");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("WI");
INSERT INTO nexus_rules (state_name, transactionTotal, dollarAmountTotal) VALUES ("WY")
